environment: DEV

log:
  outputFile: ".logs/xrf-se.log"

redis:
  database: 0
  protocol: 2
  poolSize: 5
  password: ""
  maxRetries: 1
  minIdleConns: 2
  dialTimeout: 10
  readTimeout: 15
  writeTimeout: 30
  address: "127.0.0.1:6379"

application:
  port: 8008
  readTimeout: 7s
  idleTimeout: 30s
  writeTimeout: 10s
  gracefulTimeout: 15s
  apiClientTimeout: 20s

service:
  organization:
    apiClientTimeout: 20s
    baseURL: "127.0.0.1:8009/api/v1"
